"""Add cascade delete to foreign keys

Revision ID: 48040607dd1f
Revises: 7a216a5a9481
Create Date: 2026-02-19 16:15:42.804399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48040607dd1f'
down_revision: Union[str, None] = '7a216a5a9481'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('answers_question_id_fkey'), 'answers', type_='foreignkey')
    op.create_foreign_key(None, 'answers', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('questions_theme_id_fkey'), 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'themes', ['theme_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key(op.f('questions_theme_id_fkey'), 'questions', 'themes', ['theme_id'], ['id'])
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.create_foreign_key(op.f('answers_question_id_fkey'), 'answers', 'questions', ['question_id'], ['id'])
    # ### end Alembic commands ###
